services:
  - type: web
    name: ecommerce-api
    runtime: go
    plan: free
    buildCommand: go build -o bin/main main.go
    startCommand: ./bin/main
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: "8080"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_REQUESTS
        value: "1000"
      - key: BCRYPT_COST
        value: "12"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      # Database connection - configure these in Render dashboard
      - key: DATABASE_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: ecommerce-db
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: ecommerce-db
          property: database
      - key: DATABASE_SSLMODE
        value: require
      # JWT Secret - configure in Render dashboard as secret
      - key: JWT_SECRET
        value: "1234567890poiuytrewqasdfghjklmnbvcxz"
      - key: JWT_EXPIRY
        value: 24h
    autoDeploy: true
    branch: main
    rootDir: .

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free
    postgresMajorVersion: "15"
